#!/usr/bin/env python3
"""Extract the map-object table that resolves an `.odt` object id to a model.

The id in an `.odt` record is NOT the number in an `O####_##.smdl` filename --
that was tested and refuted (only 15 of 97 ids happen to match, and the overlap
is explained by both being small integers). The real mapping is a table the
engine carries in .rodata:

  ModeGame::LoadMapObject()  @ 0x2e10b8
    memcpy's 0xC570 bytes from .rodata 0xa625c, allocates 0xC570, and loops
    w23 = 162 times. 0xC570 == 162 * 0x138, so the table is 162 entries of 312
    bytes. ModeGame::CreateMapObject @ 0x2e7460 then linear-searches it
    comparing entry word0 against the object id and formats the entry's +0x84
    string through "sk1/%s" to build the model path.

Emits `docs/object-table.md` and `src/engine/object_table.inc`.
Run with no arguments to verify against the shipping corpus.
"""

import glob
import os
import struct
import sys

RODATA_OFFSET = 0xA625C     # ModeGame::LoadMapObject's adrp 0xa6000 + #0x25c
ENTRY_SIZE = 0x138          # from the 0xC570 alloc / 162 loop count
ENTRY_COUNT = 162
NAME_OFFSET = 0x84          # CreateMapObject's `add x3, x8, #0x84` into "sk1/%s"
BLOB_SIZE = ENTRY_SIZE * ENTRY_COUNT   # 0xC570


def extract(so_path):
    """-> {object_id: model_name}. Raises if the blob does not look like itself."""
    data = open(so_path, "rb").read()
    if len(data) < RODATA_OFFSET + BLOB_SIZE:
        raise SystemExit(f"{so_path} is too small to hold the table "
                         f"(need {RODATA_OFFSET + BLOB_SIZE} bytes, have {len(data)})")
    table = {}
    for i in range(ENTRY_COUNT):
        o = RODATA_OFFSET + i * ENTRY_SIZE
        obj_id = struct.unpack_from("<i", data, o)[0]
        raw = data[o + NAME_OFFSET:o + NAME_OFFSET + 32].split(b"\0")[0]
        try:
            name = raw.decode("ascii")
        except UnicodeDecodeError:
            raise SystemExit(f"entry {i}: name at +0x{NAME_OFFSET:x} is not ASCII "
                             f"({raw!r}) -- the table offset is wrong")
        if not name or not all(" " <= c <= "~" for c in name):
            raise SystemExit(f"entry {i}: name {raw!r} is not printable "
                             f"-- the table offset is wrong")
        if obj_id in table:
            raise SystemExit(f"entry {i}: duplicate object id {obj_id}")
        table[obj_id] = name
    return table


def verify(table, dump_dir):
    """Two independent checks, each of which can actually fail."""
    ok = True

    models = set(os.path.basename(f)[:-5]
                 for f in glob.glob(os.path.join(dump_dir, "*.smdl")))
    if not models:
        print(f"FAIL: no .smdl found under {dump_dir} -- checked NOTHING, which "
              f"is not a pass", file=sys.stderr)
        return False
    missing = sorted((i, n) for i, n in table.items() if n not in models)
    print(f"  names present as a shipping model: "
          f"{len(table) - len(missing)}/{len(table)} "
          f"(checked against {len(models)} models)")
    if missing:
        print(f"    MISSING: {missing[:8]}")
        ok = False

    odts = sorted(glob.glob(os.path.join(dump_dir, "*.odt")))
    if not odts:
        print(f"FAIL: no .odt found under {dump_dir} -- checked NOTHING",
              file=sys.stderr)
        return False
    total = resolved = 0
    unresolved = set()
    for f in odts:
        d = open(f, "rb").read()
        if len(d) < 8:
            continue
        count = struct.unpack_from("<i", d, 4)[0]
        for r in range(count):
            oid = struct.unpack_from("<i", d, 0x40 + r * 0xC0 + 4)[0]
            total += 1
            if oid in table:
                resolved += 1
            else:
                unresolved.add(oid)
    print(f"  .odt placements resolved: {resolved}/{total} "
          f"across {len(odts)} rooms")
    if unresolved:
        print(f"    UNRESOLVED ids: {sorted(unresolved)[:16]}")
        ok = False
    return ok


def emit(table, md_path, inc_path):
    with open(md_path, "w") as f:
        f.write("# Map-object table (`.odt` id -> model)\n\n")
        f.write("Generated by `tools/asset/object_table.py`. Do not edit by hand.\n\n")
        f.write(f"Extracted from `ModeGame::LoadMapObject`'s .rodata blob at "
                f"`0x{RODATA_OFFSET:x}`: {ENTRY_COUNT} entries of "
                f"`0x{ENTRY_SIZE:x}` bytes, object id at +0x00 and the model "
                f"name at +0x{NAME_OFFSET:x}.\n\n")
        f.write("The id is **not** the number in the `O####_##.smdl` filename; "
                "that was tested and refuted.\n\n")
        f.write("| id | model |\n|---|---|\n")
        for i, n in sorted(table.items()):
            f.write(f"| {i} | `{n}` |\n")
    with open(inc_path, "w") as f:
        f.write("// Generated by tools/asset/object_table.py -- do not edit.\n")
        f.write("// .odt object id -> model name; see docs/object-table.md.\n")
        for i, n in sorted(table.items()):
            f.write(f'OBJ({i}, "{n}")\n')


def main(argv):
    so = argv[1] if len(argv) > 1 else "scratch/raw/libmcfandroid.so"
    dump = argv[2] if len(argv) > 2 else "scratch/dump/sk1"
    if not os.path.exists(so):
        print(f"FAIL: {so} not found -- extracted NOTHING", file=sys.stderr)
        return 2
    table = extract(so)
    print(f"map-object table: {len(table)} entries from {so}")
    ok = verify(table, dump) if os.path.isdir(dump) else None
    if ok is None:
        print(f"FAIL: {dump} does not exist, so the table was NOT verified "
              f"against any corpus", file=sys.stderr)
        return 2
    emit(table, "docs/object-table.md", "src/engine/object_table.inc")
    print("  wrote docs/object-table.md and src/engine/object_table.inc")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
