#!/usr/bin/env python3
"""Embed the complete precompiled SDL3 GPU shader pack into one build header."""

from __future__ import annotations

import argparse
from pathlib import Path


ARTIFACTS = tuple(
    f"{program}.{stage}.{extension}"
    for program in ("solid", "textured")
    for stage in ("vert", "frag")
    for extension in ("spv", "dxil", "msl")
)


def emit(input_dir: Path, output: Path) -> None:
    present = {path.name for path in input_dir.iterdir()} if input_dir.is_dir() else set()
    expected = set(ARTIFACTS)
    if present != expected:
        missing = sorted(expected - present)
        extra = sorted(present - expected)
        raise RuntimeError(
            f"scanned {len(present)} artifacts, expected {len(expected)}; "
            f"{len(missing)} missing {missing}, {len(extra)} extra {extra}"
        )

    lines = [
        "// Generated by tools/embed_shader_pack.py; do not edit.",
        "namespace mana::gpu::embedded {",
    ]
    for name in ARTIFACTS:
        data = (input_dir / name).read_bytes()
        if not data:
            raise RuntimeError(f"{name} is empty")
        symbol = name.replace(".", "_")
        encoded = ",".join(str(byte) for byte in data)
        lines.append(f"inline constexpr unsigned char {symbol}[] = {{{encoded}}};")
    lines.append("}  // namespace mana::gpu::embedded")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n")
    print("embedded 12 shader artifacts; 0 missing, 0 extra, 0 empty")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        emit(args.input_dir, args.output)
    except RuntimeError as error:
        print(f"SHADER PACK FATAL: {error}")
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
