#!/usr/bin/env python3
"""Generate src/engine/cmd_api.inc from docs/cmd-api.md.

The table is derived from the shipping binary (tools/asset/extract_cmd_api.py),
not hand-written, so it cannot drift from the real engine's Lua surface.
"""
import re, sys

RET = {'nothing': 'v', 'number': 'n', 'boolean': 'b', 'string': 's'}
ARG = {'char const*': 's', 'char*': 's', 'int': 'i', 'float': 'f',
       'bool': 'b', 'unsigned int': 'i'}

rows = []
for line in open('docs/cmd-api.md'):
    m = re.match(r'\|\s*\d+\s*\|\s*`([^`]+)`\s*\|\s*`([^`]*)`\s*\|\s*([a-z+]+)\s*\|', line)
    if not m:
        continue
    name, sig, ret = m.group(1), m.group(2), m.group(3)
    args = ''
    inner = sig[sig.find('(') + 1:sig.rfind(')')] if '(' in sig else ''
    for a in [x.strip() for x in inner.split(',') if x.strip()]:
        if a not in ARG:
            sys.exit("unmapped argument type %r in %s" % (a, sig))
        args += ARG[a]
    # A wrapper that pushes more than one kind is not representable here; fail
    # loudly rather than silently picking one.
    if ret not in RET:
        sys.exit("unmapped return type %r for %s (multi-push wrapper?)" % (ret, name))
    rows.append((name, args, RET[ret]))

if len(rows) != 200:
    sys.exit("expected 200 cmd functions, parsed %d -- docs/cmd-api.md changed shape"
             % len(rows))

with open('src/engine/cmd_api.inc', 'w') as f:
    f.write("// GENERATED by tools/gen_cmd_api.py from docs/cmd-api.md. Do not edit.\n")
    f.write("// %d functions. arg codes: i=int f=float s=string b=bool\n" % len(rows))
    f.write("// ret codes: v=void n=number b=boolean s=string\n")
    for name, args, ret in rows:
        f.write('CMD("%s", "%s", \'%c\')\n' % (name, args, ret))
print("wrote src/engine/cmd_api.inc: %d functions" % len(rows))
